# Generated by Django 4.2.23 on 2025-11-10 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=20)),
                ('deposit', models.IntegerField(default=0)),
                ('deposit_limit', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=30)),
                ('account_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portfolio.account')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.IntegerField(default=0)),
                ('buy_or_sell', models.CharField(max_length=10)),
                ('trade_quantity', models.IntegerField(default=0)),
                ('trade_price', models.IntegerField(default=0)),
                ('order_price', models.IntegerField(default=0)),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('account_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolio.member')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('average_price', models.IntegerField(default=0)),
                ('account_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.account')),
            ],
        ),
    ]
